Repository k8-proxy/k8-test-data, pull requests merged in 2020-10, with the labels that each got.

#60 RabbitMQ Publisher for Minio to S3 upload async.
  docker-compose.yaml
  rabbitmq_publisher/.env.sample
  rabbitmq_publisher/Dockerfile
  rabbitmq_publisher/main.py
  rabbitmq_publisher/requirements.txt
  rabbitmq_publisher/src/__init__.py
  rabbitmq_publisher/src/config.py
  rabbitmq_publisher/src/utils/helper.py
  rabbitmq_publisher/src/utils/minio_client.py
  rabbitmq_publisher/src/utils/rabbit_client.py
  to_s3/.env.sample
  to_s3/Dockerfile
  to_s3/README.md
  to_s3/main.py
  to_s3/requirements.txt
  to_s3/src/__init__.py
  to_s3/src/config.py
  to_s3/src/utils/__init__.py
  to_s3/src/utils/minio_client.py
  to_s3/src/utils/s3_client.py
Labels: merge conflict

#98 fix when rebuild failed donot include rebuilded file
  file_processor/src/glasswall_service.py
Labels: ready-for-review

#91 File and path storing to DB & Fetch Endpoint
  docker-compose.yaml
  s3_sync/.env.sample
  s3_sync/main.py
  s3_sync/requirements.txt
  s3_sync/src/__init__.py
  s3_sync/src/config.py
  s3_sync/src/utils/s3_client.py
  to_s3/src/__init__.py
  to_s3/src/config.py
Labels: ready-for-review

#95 Scrapyd batch processing
  README.md
  docker-compose.yaml
  file_processor/src/__init__.py
  gw_crawler/.env_sample
  gw_crawler/Dockerfile
  gw_crawler/malicious_file_crawler/Dockerfile
  gw_crawler/malicious_file_crawler/requirements.txt
  gw_crawler/malicious_file_crawler/scrapy.cfg
  gw_crawler/malicious_file_crawler/src/run_distributed_crawl.py
  gw_crawler/malicious_file_crawler/src/settings.py
  gw_crawler/malicious_file_crawler/src/spiders/dasmalwerk_crawler.py
  gw_crawler/malicious_file_crawler/src/spiders/malshare_crawler.py
  gw_crawler/malicious_file_crawler/src/spiders/tek_defence_crawler.py
  gw_crawler/malicious_file_crawler/src/spiders/virus_share.py
  gw_crawler/malicious_file_crawler/src/spiders/zoo_crawler.py
Labels: changes-requested

#97 Issue 89: Migrating gov-uk files from s3 and processing through k8-test-data file processor.
  .gitignore
  docker-compose.yaml
  file_processor/src/__init__.py
  gov_uk_file_migration/.env_sample
  gov_uk_file_migration/Dockerfile
  gov_uk_file_migration/README.md
  gov_uk_file_migration/__init__.py
  gov_uk_file_migration/main.py
  gov_uk_file_migration/requirements.txt
  gov_uk_file_migration/src/__init__.py
  gov_uk_file_migration/src/config.py
  gov_uk_file_migration/src/utils/__init__.py
  storage/.env_sample
  storage/src/__init__.py
  storage/src/config.py
  storage/src/s3_client.py
Labels: ready-for-review
